development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: jasmine-todo-list_development
  pool: 5
  username: postgres
  password: postgres

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: jasmine-todo-list_test
  pool: 5
  username: postgres
  password: postgres

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: jasmine-todo-list_production
  pool: 5
  username: postgres
  password: postgres
